In [2]:
import numpy as np
j = complex(0, 1)
m = np.array([[1/np.sqrt(3), 1/np.sqrt(7), 1/np.sqrt(7)], 
                   [-1/np.sqrt(3), -1/np.sqrt(7) + (1/np.sqrt(7))*j, -1/np.sqrt(7) - (1/np.sqrt(7))*j], 
                    [1/np.sqrt(3), - (2/np.sqrt(7))*j,  (2/np.sqrt(7))*j]])

J = np.array([[-1, 0, 0], 
                   [0, -1 + j, 0], 
                    [0, 0, -1 -j]])
minv = np.array([[4*np.sqrt(3), 2*np.sqrt(3), np.sqrt(3)], 
                   [-(np.sqrt(7)/2)*(3+j), -(np.sqrt(7)/2)*(2+j), -(np.sqrt(7)/2)], 
                    [(np.sqrt(7)/2)*(-3+j), (np.sqrt(7)/2)*(-2+j),  -(np.sqrt(7)/2)]])

np.dot(np.dot(m, J), minv)

array([[ 0.000000e+00-3.08902599e-17j,  1.000000e+00-1.54451300e-17j,
        -1.544513e-17-1.54451300e-17j],
       [ 2.000000e+00+9.26707798e-17j,  0.000000e+00+6.17805199e-17j,
         1.000000e+00+3.08902599e-17j],
       [-8.000000e+00-1.23561040e-16j, -4.000000e+00-9.26707798e-17j,
        -3.000000e+00-3.08902599e-17j]])

In [4]:
j = complex(0, 1)
m = np.array([[1, 0,  -1/np.sqrt(2)], 
                   [0, 1, 0], 
                    [0, 0,  1/np.sqrt(2)]])

J = np.array([[1, 0, 0], 
                   [0, 1, 0], 
                    [0, 0, 2]])
minv = np.array([[1, 0,  1], 
                   [0, 1, 0], 
                    [0, 0,  np.sqrt(2)]])

np.dot(np.dot(m, J), minv)

array([[ 1.,  0., -1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  2.]])

In [3]:
j = complex(0, 1)
m = np.array([[1, 0,  0], 
                   [0, -4/(np.sqrt(41)), -3/5], 
                    [0, 5/(np.sqrt(41)),  4/5]])

J = np.array([[0, 1, 0], 
                   [0, 0, 1], 
                    [0, 0, 0]])
minv = np.array([[1, 0,  0], 
                   [0, -4*(np.sqrt(41)), -3*(np.sqrt(41))], 
                    [0, 25,  16]])

np.dot(np.dot(m, J), minv)

array([[  0.        , -25.61249695, -19.20937271],
       [  0.        , -15.61737619,  -9.99512076],
       [  0.        ,  19.52172024,  12.49390095]])